sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"username\":\"aaa\",\"password\":\"111\"},{\"id\":98, \"username\":\"bbb\",\"password\":\"222\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.254.133
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url: 
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh

---
spring:
  profiles: user1

server:
  port: 8101

#---
#spring:
#  profiles: user2
#
#server:
#  port: 8102
